services:

  api:
    build:
      context: ./backend
    container_name: zulmach_api
    restart: always
    ports:
      - "8000:8000"
    depends_on:
      - postgres
      - redis

  bot:
    build:
      context: ./bot
    container_name: zulmach_bot
    restart: always
    env_file:
      - .env
    depends_on:
      - postgres
      - redis

  postgres:
    image: postgres:16
    container_name: zulmach_postgres
    restart: always
    environment:
      POSTGRES_DB: zulmach
      POSTGRES_USER: zulmach
      POSTGRES_PASSWORD: change_this_password
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  redis:
    image: redis:7
    container_name: zulmach_redis
    restart: always
    ports:
      - "6379:6379"


volumes:
  postgres_data:
